### ISSUE TITLE
Menu titles Overwriting Settings

### ISSUE THREAD

**Issue by EMJB** [OpenViX/enigma2-skins#1]
I hope I have raised this in the right place - please advise me if not.

I am using the default OpenVix skin using OpenVix 5.1.032 and ABM 3.1 on an Xtrend 10K. In https://www.world-of-satellite.com/showthread.php?59860 I raised an issue with the ABM menu - text describing options overwrites the associate settings. The response in that thread was that it was a skin rather than ABM issue. This occurs in several places among the ABM menus, not just the in the example screenshot posted there.

**Comment by AbuBaniaz** [comment]
We have modified ABM so that it is not as "wordy".

You should try the Simple 1080 skin.

**Comment by EMJB** [comment]
So it was an ABM problem after all?? When will the new version be available so I can use it for screenshots in the user guide?

I am not happy with having to change skin, particularly in view of the risk that I find more problems resulting in advice to change back. If "Simple 1080" has no problems, why is that not the default skin?

I appreciate there are problems when plug-ins such as ABM are not specific to OpenVix, but from a user perspective ABM is "bundled" with OpenVix so it should work "out-of-the-box", and not require skin changes etc. One penalty of not resolving these and other issues is the time spent answering issues such as this.

As an aside, a word of thanks for raising problems that you accept needs action would not go amiss.

**Comment by Huevos** [comment]
No it is not an ABM problem, it is a skin issue. There is not enough space for the text in a halfscreen skin. Changing the text here though to the minimum will help skins that have limited space available.

The new version is available on github as soon as it is committed.
